### ISSUE TITLE
No output when "Submit for Processing" clicked.

### ISSUE THREAD

**Issue by kylemd** [hack4impact/cls#41]
Hi!

I've recently sold my business and need to do up a timesheet for hours worked since the sale and this tool fits the bill. However, I can't seem to get it to work. I'm not a web developer, so if I've missed something simple it might be worth putting in the readme :)

The following error appears when running both online and locally:

`Could not read source map for file:///C:/Users/kyle/Downloads/billing/cls/static/scripts/lib/bootstrap-select.min.js: ENOENT: no such file or directory, open 'c:\Users\kyle\Downloads\billing\cls\static\scripts\lib\bootstrap-select.js.map'
Could not read source map for file:///C:/Users/kyle/Downloads/billing/cls/static/scripts/lib/prunecluster.js: ENOENT: no such file or directory, open 'c:\Users\kyle\Downloads\billing\cls\static\scripts\lib\PruneCluster.js.map'
Done reading file
static/scripts/upload-v2.js:67
Uncaught TypeError TypeError: Cannot read properties of undefined (reading 'data')
    at <anonymous> (c:\Users\kyle\Downloads\billing\cls\static\scripts\csv-v2.js:35:39)
    at dispatch (c:\Users\kyle\Downloads\billing\cls\static\scripts\lib\jquery.min.js:3:10315)
    at q.handle (c:\Users\kyle\Downloads\billing\cls\static\scripts\lib\jquery.min.js:3:8342)`

Is there anything that can be done to fix this?

**Comment by kylemd** [comment]
Further information:

It seems this git isn't loading current takeout json files correctly. See [this fork](https://github.com/koryp/Google-Location-History-Parser) that has it fixed.

This fork however has a separate issue which would be outside the scope of this one.
